addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
- CXX=g++-4.8

branches:
  only:
    - master

cache:
  directories:
    - node_modules

script:
  - npm run build.prod
  - "lineman spec-ci"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master

node_js:
- 8.0
