language: node_js
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
- CXX=g++-4.8
node_js:
- 8.0
branches:
  only:
    - master
cache:
  directories:
    - node_modules
script:
  - "lineman spec-ci"
  - npm run build.prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
